version: '3.8'

services:
  app:
    build:
      context: .
      args:
        user: laravel
        uid: 1000
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/conf.d:/usr/local/etc/php/conf.d
    environment:
      - APP_ENV=local
      - APP_KEY=
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
    networks:
      - laravel
    depends_on:
      - db
      - redis

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - laravel
    depends_on:
      - app

  db:
    image: mariadb:10.11
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel

  scheduler:
    build: .
    container_name: scheduler
    command: >
      sh -c "while [ true ]
      do
        php /var/www/artisan schedule:run --verbose --no-interaction &
        sleep 60
      done"
    restart: unless-stopped
    volumes:
      - ./:/var/www
    networks:
      - laravel
    depends_on:
      - app
      - db

  queue:
    build: .
    container_name: queue
    command: php /var/www/artisan queue:work --sleep=3 --tries=3
    restart: unless-stopped
    volumes:
      - ./:/var/www
    networks:
      - laravel
    depends_on:
      - app
      - db

volumes:
  dbdata:
    driver: local

networks:
  laravel:
    driver: bridge